name: "build channel-sender"
on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
    paths:
      - 'channel-sender/**'

  pull_request:
    branches:
      - main
    paths:
      - 'channel-sender/**'

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./channel-sender

    steps:
      - name: Generate a token of Github APP
        id: generate_token
        if: github.ref == 'refs/heads/main'
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID_ADMIN_GITHUB }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_ADMIN_GITHUB }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: github.ref != 'refs/heads/main'

      - name: Verify Conventional Commits
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up NodeJS
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: './channel-sender/.nvmrc'
      - name: Set up Semantic Release
        if: github.ref == 'refs/heads/main'
        run: npm -g install @semantic-release/git semantic-release
      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Set up Elixir
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          version-type: strict
          version-file: "./channel-sender/.tool-versions"
      - name: Restore dependencies cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
        env:
          SKIP_GIT_HOOKS: 'true'
      - name: Code analysis
        run: mix credo --strict && mix dialyzer
      - name: Test generated code
        run: mix test
      - name: Tests & Coverage (main)
        if: github.ref == 'refs/heads/main'
        run: mix coveralls.github --umbrella
        env:
          CI_ENV: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tests & Coverage (pull requests)
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        run: mix coveralls.lcov --umbrella
        env:
          CI_ENV: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PR Report tool
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # v1.1.0
      - name: Validate code coverage
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: zgosalvez/github-actions-report-lcov@4eb99c09644c30cceb609413620bd9e1bf80ee79 # v6.0.1
        with:
          coverage-files: ./channel-sender/cover/lcov.info
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
